### ISSUE TITLE
Plugin not suggested by Idea to install

### ISSUE THREAD

**Issue by gildor** [JetBrains/intellij-hocon#1]
If you try to open .conf file in Idea, you will see the suggestion to install a plugin for this file type.
But in the list you will see only Scala plugin, no standalone HOCON.

Currently, the only way to go to plugins repo and install the plugin manually, but only if you know that this plugin exists.

**Comment by HannyTufail** [comment]
You can install the _**SCALA plugin**_ to get support of _**HOCON**_ now. As its documentation says, 

> The Scala plugin extends IntelliJ IDEA’s toolset with support for Scala, sbt, Scala.js, Hocon, and Play Framework. Support for Scala, sbt and Hocon is available for free in IntelliJ IDEA Community Edition, while support for Play Framework and Scala.js is available only in IntelliJ IDEA Ultimate.

**Comment by gildor** [comment]
@HannyTufail  Of course, I understand this. But I don't want to install Scala plugin, This plugin provides support of HOCON files as a separate plugin, and all the point of this to allow install support for relatively popular config format without the need to install whole Scala plugin.
The problem that plugin is not suggested by IDEA as a plugin that provides support for HOCON and you have to search it manually in plugins repository

**Comment by mutcianm** [comment]
@gildor @HannyTufail We're planning to completely extract HOCON support to a standalone plugin, so eventually(2018.3 if all goes well) it will be cut from the Scala plugin.

**Comment by mutcianm** [comment]
Fixed 
![2018-08-02-135625_574x359_scrot](https://user-images.githubusercontent.com/1345782/43579779-e2d9a30a-965b-11e8-8f75-bfd37dbdf363.png)
