### ISSUE TITLE
Jump to source of file by CMD+click

### ISSUE THREAD

**Issue by ihostage** [JetBrains/intellij-hocon#13]
For example, I have the next configuration:
```
play {
  modules.enabled += foo.bar.MyModule
}
```

IDEA successfully found class `MyModule` in HOCON file by "Find usages" (ALT+F7).
But I can't jump to the source of `MyModule` by CMD+click in HOCON editor.

PS: This feature work fine for the editor of properties files. For example for `application.properties` with the following content:
```
module=foo.bar.MyModule
```

**Comment by ghik** [comment]
Hello, unfortunately I can't reproduce this as well... It would be best if you could create a simple reproduction project.

**Comment by ihostage** [comment]
https://github.com/ihostage/intellij-hocon-13

**Comment by ghik** [comment]
Works fine in my IDEA Community 2019.1, as you can see in the GIF below:

![hocon_navigation](https://user-images.githubusercontent.com/1022675/56580699-73fd5d80-65d3-11e9-8078-90ae810c329d.gif)

Just like in #12, this must be some bad interaction between plugins you have installed in your Ultimate edition.

**Comment by ihostage** [comment]
😢I tried reinstall IDEA and plugin, but it not help.
Have any other ideas?

**Comment by ghik** [comment]
Can you go through file types in `Settings -> Editor -> File Types` to see whether files with `*.conf` extension have other associations than HOCON?

**Comment by ihostage** [comment]
https://www.jetbrains.com/help/idea/smarty.html
SmartyConfig 🤦‍♂️
Sorry 😞
