### ISSUE TITLE
Make Hocon plugin compatible with other IDEs

### ISSUE THREAD

**Issue by admiral0** [JetBrains/intellij-hocon#2]
HOCON is a spec, it has implementations for c++ (cpp-hocon), python (pyhocon) and scala.

Currently it is impossible to use this plugin on CLion or PyCharm

**Comment by chuxi** [comment]
I also want to use it for c/c++ projects!
hocon is a great configuration format.

**Comment by isengrim613** [comment]
Would like this for Rider
