### ISSUE TITLE
Does not work with Ultimate 2019.3 EAP 

### ISSUE THREAD

**Issue by kool79** [JetBrains/intellij-hocon#20]
Incompatible with the current IDEA verion
IntelliJ IDEA 2019.3 EAP (Ultimate Edition)
Build #IU-193.2956.37, built on September 11, 2019
IntelliJ IDEA EAP User
Expiration date: October 11, 2019
Runtime version: 11.0.4+12-b462.3 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by niktrop** [comment]
@mutcianm Does it need `until-build` at all? I thought uses only some basic API that is unlikely to change.

**Comment by narma** [comment]
Miss this plugin too.

**Comment by NickAcPT** [comment]
Would also love this plugin released for 2019.3 EAP. 👍 
Tried building it myself but wasn't able to do it correctly mainly due to the fact that there's no build instructions and because I'm a bit lost when working with Scala.

**Comment by ghik** [comment]
Released 2019.3.1
